# ScreenStreamer by YangHaitao

# log level
# a value of (DEBUG, INFO, WARN, ERROR)
log_level: INFO
log_path: logs

# host and port that you will use other device to request this service
server_host: 0.0.0.0
server_port: 8080

# how many threads you want to run goroutines
threads: 5

# target fps
fps: 30
# target jpeg quality
quality: 96
# broadcast,true for broadcast, false for point to point
broadcast: false
# screenshot image
# left offset, 0 is default
# top offset, 0 is default
# width, 0 is default, means auto
# height, 0 is default, means auto
left: 0
top: 0
width: 0
height: 0
# resize function is not work now, so ignore this two options
resize_width: 0
resize_height: 0

# don't change this options, if you don't know how it works
tasks_queue_size: 1
buffer_queue_size: 0
images_queue_size: 0
convert_buffer_size: 1
convert_images_size: 1

# to_sbs, convert 2d image to side-by-side images
to_sbs: false
# cursor, capture cursor or not
cursor: false

# how many screen shoters to work, less than 10
shot: 1
# alpha is an option to make the fps stable
# every frame sleep +/- (alpha / 100) * (1 / fps) senonds
alpha: 15
# how many image converter to work, less than 10
convert: 3
# the application work mode
# single, just a worker with shoter & converter functions
# single-single, a shoter and a converter
# single-multi, a shoter and multi converters
# multi-multi, multi shoter and multi converters
# sync-single-multi, a shoter and multi converters, shoter and converters works synchronizely
# sync-multi-multi, multi shoters and multi converters, shoters and converters works synchronizely
mode: sync-single-multi

# fps 22 quality 95 - 100 1600 * 900 threads 5 convert 4
